name: Auftragsbearbeitung Build

on:
  push:
    branches:
      - main
      - development

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: maxbrennemann
  APP_NAME: auftragsbearbeitung
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Determine channel tag (prod/dev)
        id: channel
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "channel=prod" >> "$GITHUB_OUTPUT"
            echo "tag_latest=prod-latest" >> "$GITHUB_OUTPUT"
          else
            echo "channel=dev" >> "$GITHUB_OUTPUT"
            echo "tag_latest=dev-latest" >> "$GITHUB_OUTPUT"
          fi

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: network=host
          buildkitd-flags: --debug
          use: true

      - name: Build and push PHP image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .config/Dockerfile.prod
          push: true
          target: php-base
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.APP_NAME }}/php-base:cache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.APP_NAME }}/php-base:cache,mode=max
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.APP_NAME }}/php-base:${{ steps.channel.outputs.tag_latest }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.APP_NAME }}/php-base:${{ github.sha }}

      - name: Build and push Web image (optional)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .config/Dockerfile.prod
          push: true
          target: web-base
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.APP_NAME }}/web-base:cache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.APP_NAME }}/web-base:cache,mode=max
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.APP_NAME }}/web-base:${{ steps.channel.outputs.tag_latest }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.APP_NAME }}/web-base:${{ github.sha }}

      - name: Trigger Deployment in Private Repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: maxBrennemann/internal-scripts
          event-type: deploy-event
          client-payload: '{"branch": "${{ github.ref_name }}"}'
